require './lib/checkout'
require './lib/item'
require './lib/promotional_rule'
require './lib/promotional_rule/order'
require './lib/promotional_rule/buy_two_tchs'
require './lib/promotional_rule/spend_over_sixty'